// Intentionally absurd single-word prompts, including playful invented words.
const WORDS_ABSURD = [
  { word: 'Bąkonauta', category: 'Podejrzana załoga', hint: 'NAPĘD WŁASNY' },
  { word: 'Kibeltron', category: 'Podejrzana załoga', hint: 'ROBOT NA TRONIE' },
  { word: 'Januszozaur', category: 'Podejrzana załoga', hint: 'PREHISTORYCZNA PROMOCJA' },
  { word: 'Skarpetozjad', category: 'Podejrzana załoga', hint: 'GINIE TYLKO JEDNA' },
  { word: 'Parówkozaur', category: 'Podejrzana załoga', hint: 'JURAJSKIE ŚNIADANIE' },
  { word: 'Glutożerca', category: 'Podejrzana załoga', hint: 'LEPKA DIETA' },
  { word: 'Glutoplazma', category: 'Dziwne substancje', hint: 'DUCH SIĘ ROZLAŁ' },
  { word: 'Bąkolina', category: 'Dziwne substancje', hint: 'AROMATYCZNE LEPIENIE' },
  { word: 'Kisielobeton', category: 'Dziwne substancje', hint: 'BUDYNEK SIĘ TRZĘSIE' },
  { word: 'Serolawa', category: 'Dziwne substancje', hint: 'WYBUCH ZAPIEKANKI' },
  { word: 'Majonezium', category: 'Dziwne substancje', hint: 'PIERWIASTEK SAŁATKOWY' },
  { word: 'Brokatoplazma', category: 'Dziwne substancje', hint: 'NAWIEDZONA DYSKOTEKA' },
  { word: 'Gaciomiot', category: 'Wynalazki bez patentu', hint: 'BIELIZNA NA ORBICIE' },
  { word: 'Bąkometr', category: 'Wynalazki bez patentu', hint: 'POMIAR WSTYDU' },
  { word: 'Klapkofon', category: 'Wynalazki bez patentu', hint: 'ROZMOWA Z PODESZWY' },
  { word: 'Pierogowirówka', category: 'Wynalazki bez patentu', hint: 'FARSZ NA OBROTACH' },
  { word: 'Nosodmuch', category: 'Wynalazki bez patentu', hint: 'KATAR POD CIŚNIENIEM' },
  { word: 'Chrapogłośnik', category: 'Wynalazki bez patentu', hint: 'KONCERT Z SYPIALNI' },
  { word: 'Kibelgedon', category: 'Katastrofy codzienne', hint: 'OSTATNIA ROLKA' },
  { word: 'Bąkonado', category: 'Katastrofy codzienne', hint: 'NIE OTWIERAJ OKNA' },
  { word: 'Skarpetokalipsa', category: 'Katastrofy codzienne', hint: 'ANI JEDNEJ PARY' },
  { word: 'Kacopokalipsa', category: 'Katastrofy codzienne', hint: 'RANEK PO KOŃCU ŚWIATA' },
  { word: 'Rosółnami', category: 'Katastrofy codzienne', hint: 'FALA Z MAKARONEM' },
  { word: 'Majonezagedon', category: 'Katastrofy codzienne', hint: 'SAŁATKA PRZEJĘŁA KUCHNIĘ' },
  { word: 'Parawanokracja', category: 'Wakacyjne odklejenie', hint: 'WŁADZA NAD PIASKIEM' },
  { word: 'Leżakoza', category: 'Wakacyjne odklejenie', hint: 'NIEULECZALNY ODPOCZYNEK' },
  { word: 'Klapkoportacja', category: 'Wakacyjne odklejenie', hint: 'Z BASENU PROSTO DO BUFETU' },
  { word: 'Ręcznikowojna', category: 'Wakacyjne odklejenie', hint: 'REZERWACJA O ŚWICIE' },
  { word: 'Drinkozauroid', category: 'Wakacyjne odklejenie', hint: 'BESTIA PRZY BARZE' },
  { word: 'Plażofobia', category: 'Wakacyjne odklejenie', hint: 'PIASEK MNIE OCENIA' },
  { word: 'Pierogokracja', category: 'Kuchenne odklejenie', hint: 'RZĄDY FARSZU' },
  { word: 'Kebaboskop', category: 'Kuchenne odklejenie', hint: 'WRÓŻBA Z SOSU' },
  { word: 'Ziemniakonauta', category: 'Kuchenne odklejenie', hint: 'BULWA W KOSMOSIE' },
  { word: 'Ogórkultysta', category: 'Kuchenne odklejenie', hint: 'TAJEMNY OBRZĘD W SŁOIKU' },
  { word: 'Frytkonauta', category: 'Kuchenne odklejenie', hint: 'MISJA W GŁĘBOKIM OLEJU' },
  { word: 'Schabosfera', category: 'Kuchenne odklejenie', hint: 'ATMOSFERA W PANIERCE' },
];
