const WORDS_COUNTRY = [
{ word: "Polska", category: "Państwa", hint: "EUROPA" },
{ word: "Niemcy", category: "Państwa", hint: "EUROPA" },
{ word: "Francja", category: "Państwa", hint: "EUROPA" },
{ word: "Hiszpania", category: "Państwa", hint: "EUROPA" },
{ word: "Włochy", category: "Państwa", hint: "EUROPA" },
{ word: "Portugalia", category: "Państwa", hint: "EUROPA" },
{ word: "Holandia", category: "Państwa", hint: "EUROPA" },
{ word: "Belgia", category: "Państwa", hint: "EUROPA" },
{ word: "Austria", category: "Państwa", hint: "EUROPA" },
{ word: "Szwajcaria", category: "Państwa", hint: "EUROPA" },
{ word: "Szwecja", category: "Państwa", hint: "SKANDYNAWIA" },
{ word: "Norwegia", category: "Państwa", hint: "SKANDYNAWIA" },
{ word: "Finlandia", category: "Państwa", hint: "SKANDYNAWIA" },
{ word: "Dania", category: "Państwa", hint: "SKANDYNAWIA" },
{ word: "Islandia", category: "Państwa", hint: "WYSPA" },
{ word: "Czechy", category: "Państwa", hint: "EUROPA" },
{ word: "Słowacja", category: "Państwa", hint: "EUROPA" },
{ word: "Węgry", category: "Państwa", hint: "EUROPA" },
{ word: "Rumunia", category: "Państwa", hint: "BAŁKANY" },
{ word: "Bułgaria", category: "Państwa", hint: "BAŁKANY" },
{ word: "Grecja", category: "Państwa", hint: "BAŁKANY" },
{ word: "Chorwacja", category: "Państwa", hint: "BAŁKANY" },
{ word: "Serbia", category: "Państwa", hint: "BAŁKANY" },
{ word: "Ukraina", category: "Państwa", hint: "EUROPA" },
{ word: "Białoruś", category: "Państwa", hint: "EUROPA" },
{ word: "Rosja", category: "Państwa", hint: "EUROAZJA" },
{ word: "Turcja", category: "Państwa", hint: "EUROAZJA" },
{ word: "USA", category: "Państwa", hint: "AMERYKA" },
{ word: "Kanada", category: "Państwa", hint: "AMERYKA" },
{ word: "Meksyk", category: "Państwa", hint: "AMERYKA" },
{ word: "Brazylia", category: "Państwa", hint: "AMERYKA POŁUDNIOWA" },
{ word: "Argentyna", category: "Państwa", hint: "AMERYKA POŁUDNIOWA" },
{ word: "Chile", category: "Państwa", hint: "AMERYKA POŁUDNIOWA" },
{ word: "Peru", category: "Państwa", hint: "AMERYKA POŁUDNIOWA" },
{ word: "Kolumbia", category: "Państwa", hint: "AMERYKA POŁUDNIOWA" },
{ word: "Wenezuela", category: "Państwa", hint: "AMERYKA POŁUDNIOWA" },
{ word: "Kuba", category: "Państwa", hint: "KARAIBY" },
{ word: "Japonia", category: "Państwa", hint: "AZJA" },
{ word: "Chiny", category: "Państwa", hint: "AZJA" },
{ word: "Indie", category: "Państwa", hint: "AZJA" },
{ word: "Korea Południowa", category: "Państwa", hint: "AZJA" },
{ word: "Korea Północna", category: "Państwa", hint: "AZJA" },
{ word: "Tajlandia", category: "Państwa", hint: "AZJA" },
{ word: "Wietnam", category: "Państwa", hint: "AZJA" },
{ word: "Indonezja", category: "Państwa", hint: "AZJA" },
{ word: "Malezja", category: "Państwa", hint: "AZJA" },
{ word: "Singapur", category: "Państwa", hint: "MIASTO-PAŃSTWO" },
{ word: "Filipiny", category: "Państwa", hint: "AZJA" },
{ word: "Pakistan", category: "Państwa", hint: "AZJA" },
{ word: "Arabia Saudyjska", category: "Państwa", hint: "BLISKI WSCHÓD" },
{ word: "Zjednoczone Emiraty Arabskie", category: "Państwa", hint: "BLISKI WSCHÓD" },
{ word: "Izrael", category: "Państwa", hint: "BLISKI WSCHÓD" },
{ word: "Egipt", category: "Państwa", hint: "AFRYKA" },
{ word: "Maroko", category: "Państwa", hint: "AFRYKA" },
{ word: "Tunezja", category: "Państwa", hint: "AFRYKA" },
{ word: "RPA", category: "Państwa", hint: "AFRYKA" },
{ word: "Nigeria", category: "Państwa", hint: "AFRYKA" },
{ word: "Kenia", category: "Państwa", hint: "AFRYKA" },
{ word: "Etiopia", category: "Państwa", hint: "AFRYKA" },
{ word: "Australia", category: "Państwa", hint: "OCEANIA" },
{ word: "Nowa Zelandia", category: "Państwa", hint: "OCEANIA" },
{ word: "Kazachstan", category: "Państwa", hint: "AZJA CENTRALNA" },
{ word: "Mongolia", category: "Państwa", hint: "AZJA" },
{ word: "Luksemburg", category: "Państwa", hint: "EUROPA" },
{ word: "Irlandia", category: "Państwa", hint: "WYSPA" },
{ word: "Wielka Brytania", category: "Państwa", hint: "WYSPA" }
];