const WORDS_DEFAULT = [
    { word: "TELEFON", category: "Elektronika", hint: "KONTAKT" },
    { word: "KOMPUTER", category: "Elektronika", hint: "PRACA" },
    { word: "LAPTOP", category: "Elektronika", hint: "MOBILNY" },
    { word: "TABLET", category: "Elektronika", hint: "DOTYK" },
    { word: "MONITOR", category: "Elektronika", hint: "OBRAZ" },
    { word: "KLAWIATURA", category: "Elektronika", hint: "PISANIE" },
    { word: "MYSZKA", category: "Elektronika", hint: "KURSOR" },
    { word: "DRUKARKA", category: "Elektronika", hint: "PAPIER" },
    { word: "GŁOŚNIK", category: "Elektronika", hint: "DŹWIĘK" },
    { word: "SŁUCHAWKI", category: "Elektronika", hint: "MUZYKA" },

    { word: "SAMOCHÓD", category: "Transport", hint: "DROGA" },
    { word: "ROWer", category: "Transport", hint: "PEDAŁY" },
    { word: "AUTOBUS", category: "Transport", hint: "PRZYSTANEK" },
    { word: "POCIĄG", category: "Transport", hint: "TOROWISKO" },
    { word: "SAMOLOT", category: "Transport", hint: "LOT" },
    { word: "STATEK", category: "Transport", hint: "WODA" },
    { word: "MOTOR", category: "Transport", hint: "DWA KOŁA" },
    { word: "HELIKOPTER", category: "Transport", hint: "ŚMIGŁO" },
    { word: "TRAKTOR", category: "Transport", hint: "POLE" },
    { word: "METRO", category: "Transport", hint: "POD ZIEMIĄ" },

    { word: "ŁÓŻKO", category: "Meble", hint: "SEN" },
    { word: "KANAPA", category: "Meble", hint: "SALON" },
    { word: "FOTEL", category: "Meble", hint: "SIEDZENIE" },
    { word: "KRZESŁO", category: "Meble", hint: "OPARCIE" },
    { word: "STÓŁ", category: "Meble", hint: "BLAT" },
    { word: "BIURKO", category: "Meble", hint: "PRACA" },
    { word: "SZAFA", category: "Meble", hint: "UBRANIA" },
    { word: "KOMODA", category: "Meble", hint: "SZUFLADY" },
    { word: "REGAŁ", category: "Meble", hint: "PÓŁKI" },
    { word: "PÓŁKA", category: "Meble", hint: "ŚCIANA" },

    { word: "MŁOTEK", category: "Narzędzia", hint: "GWÓŹDŹ" },
    { word: "ŚRUBOKRĘT", category: "Narzędzia", hint: "ŚRUBA" },
    { word: "KLUCZ FRANCUSKI", category: "Narzędzia", hint: "NAPRAWA" },
    { word: "WIERTARKA", category: "Narzędzia", hint: "OTWÓR" },
    { word: "PIŁA", category: "Narzędzia", hint: "DREWNO" },
    { word: "MIARKA", category: "Narzędzia", hint: "DŁUGOŚĆ" },
    { word: "POZIOMICA", category: "Narzędzia", hint: "PROSTO" },
    { word: "SZCZYPCE", category: "Narzędzia", hint: "CHWYT" },
    { word: "SEKATOR", category: "Narzędzia", hint: "OGRÓD" },
    { word: "ŁOPATA", category: "Narzędzia", hint: "KOPANIE" },

    { word: "SZPITAL", category: "Budynki", hint: "ZDROWIE" },
    { word: "SZKOŁA", category: "Budynki", hint: "NAUKA" },
    { word: "BANK", category: "Budynki", hint: "PIENIĄDZE" },
    { word: "HOTEL", category: "Budynki", hint: "NOCLEG" },
    { word: "LOTNISKO", category: "Budynki", hint: "SAMOLOTY" },
    { word: "DWORZEC", category: "Budynki", hint: "PODRÓŻ" },
    { word: "BIBLIOTEKA", category: "Budynki", hint: "KSIĄŻKI" },
    { word: "MUZEUM", category: "Budynki", hint: "HISTORIA" },
    { word: "KINO", category: "Budynki", hint: "FILM" },
    { word: "TEATR", category: "Budynki", hint: "SCENA" },

    { word: "LEKARZ", category: "Zawody", hint: "PACJENT" },
    { word: "NAUCZYCIEL", category: "Zawody", hint: "UCZEŃ" },
    { word: "POLICJANT", category: "Zawody", hint: "PRAWO" },
    { word: "STRAŻAK", category: "Zawody", hint: "OGIEŃ" },
    { word: "PILOT", category: "Zawody", hint: "SAMOLOT" },
    { word: "KUCHARZ", category: "Zawody", hint: "KUCHNIA" },
    { word: "MECHANIK", category: "Zawody", hint: "NAPRAWA" },
    { word: "FRYZJER", category: "Zawody", hint: "WŁOSY" },
    { word: "PROGRAMISTA", category: "Zawody", hint: "KOD" },
    { word: "ARCHITEKT", category: "Zawody", hint: "PROJEKT" },

    { word: "PIŁKA", category: "Sport", hint: "MECZ" },
    { word: "SIŁOWNIA", category: "Sport", hint: "TRENING" },
    { word: "BIEŻNIA", category: "Sport", hint: "BIEGANIE" },
    { word: "MEDAL", category: "Sport", hint: "ZWYCIĘSTWO" },
    { word: "PŁYWANIE", category: "Sport", hint: "WODA" },
    { word: "NARTY", category: "Sport", hint: "ZIMA" },
    { word: "DESKOROLKA", category: "Sport", hint: "TRIKI" },
    { word: "HANTLE", category: "Sport", hint: "CIĘŻAR" },
    { word: "BOISKO", category: "Sport", hint: "MECZ" },
    { word: "TENIS", category: "Sport", hint: "RAKIETKA" },

    { word: "BURZA", category: "Pogoda", hint: "PIORUN" },
    { word: "DESZCZ", category: "Pogoda", hint: "KROPLE" },
    { word: "ŚNIEG", category: "Pogoda", hint: "ZIMA" },
    { word: "WIATR", category: "Pogoda", hint: "PODMUCH" },
    { word: "MGŁA", category: "Pogoda", hint: "WIDOCZNOŚĆ" },
    { word: "GRAD", category: "Pogoda", hint: "LODOWE KULKI" },
    { word: "TĘCZA", category: "Pogoda", hint: "KOLORY" },
    { word: "UPAŁ", category: "Pogoda", hint: "GORĄCO" },
    { word: "MRÓZ", category: "Pogoda", hint: "ZIMNO" },
    { word: "HURAGAN", category: "Pogoda", hint: "ŻYWIOŁ" },

    { word: "KSIĘŻYC", category: "Kosmos", hint: "NOC" },
    { word: "SŁOŃCE", category: "Kosmos", hint: "ŚWIATŁO" },
    { word: "PLANETA", category: "Kosmos", hint: "ORBITA" },
    { word: "GWIAZDA", category: "Kosmos", hint: "KOSMOS" },
    { word: "SATELITA", category: "Kosmos", hint: "ORBITA" },
    { word: "ASTEROIDA", category: "Kosmos", hint: "SKAŁA" },
    { word: "GALAKTYKA", category: "Kosmos", hint: "DROGA MLECZNA" },
    { word: "KOMETa", category: "Kosmos", hint: "OGON" },
    { word: "ASTRONAUTA", category: "Kosmos", hint: "HEŁM" },
    { word: "TELESKOP", category: "Kosmos", hint: "OBSERWACJA" },

    { word: "KOSZULKA", category: "Ubrania", hint: "RĘKAWY" },
    { word: "SPODNIE", category: "Ubrania", hint: "NOGAWKI" },
    { word: "BLUZA", category: "Ubrania", hint: "KAPTUR" },
    { word: "KURTKA", category: "Ubrania", hint: "ZIMA" },
    { word: "CZAPKA", category: "Ubrania", hint: "GŁOWA" },
    { word: "SZALIK", category: "Ubrania", hint: "SZYJA" },
    { word: "RĘKAWICZKI", category: "Ubrania", hint: "DŁONIE" },
    { word: "SKARPETKI", category: "Ubrania", hint: "STOPY" },
    { word: "BUTY", category: "Ubrania", hint: "CHODZENIE" },
    { word: "PASEK", category: "Ubrania", hint: "SPODNIE" },

    { word: "GITARA", category: "Instrumenty", hint: "STRUNY" },
    { word: "PIANINO", category: "Instrumenty", hint: "KLAWISZE" },
    { word: "SKRZYPCE", category: "Instrumenty", hint: "SMYCZEK" },
    { word: "TRĄBKA", category: "Instrumenty", hint: "DĘTY" },
    { word: "PERKUSJA", category: "Instrumenty", hint: "RYTM" },
    { word: "FLET", category: "Instrumenty", hint: "DĘTY" },
    { word: "AKORDEON", category: "Instrumenty", hint: "MIESZEK" },
    { word: "HARFA", category: "Instrumenty", hint: "STRUNY" },
    { word: "SAKSOFON", category: "Instrumenty", hint: "JAZZ" },
    { word: "WIOLONCZELA", category: "Instrumenty", hint: "ORKIESTRA" },

    { word: "RÓŻA", category: "Rośliny", hint: "KOLCE" },
    { word: "TULIPAN", category: "Rośliny", hint: "WIOSNA" },
    { word: "SŁONECZNIK", category: "Rośliny", hint: "ŻÓŁTY" },
    { word: "KAKTUS", category: "Rośliny", hint: "PUSTYNIA" },
    { word: "STORCZYK", category: "Rośliny", hint: "DONICZKA" },
    { word: "PAPROĆ", category: "Rośliny", hint: "LIŚCIE" },
    { word: "DĄB", category: "Rośliny", hint: "DRZEWO" },
    { word: "SOSNA", category: "Rośliny", hint: "IGŁY" },
    { word: "BRZOZA", category: "Rośliny", hint: "BIAŁA KORA" },
    { word: "KLON", category: "Rośliny", hint: "LIŚĆ" },

    { word: "MOST", category: "Konstrukcje", hint: "RZEKA" },
    { word: "TUNEL", category: "Konstrukcje", hint: "POD ZIEMIĄ" },
    { word: "LATARNIA", category: "Konstrukcje", hint: "ŚWIATŁO" }


];