const WORDS_ANIMAL = [
    {   word: "USA",   category: "Państwa",    hint: "AMERYKA"  },
    {   word: "USA",   category: "Państwa",    hint: "AMERYKA"  },
    {   word: "USA",   category: "Państwa",    hint: "AMERYKA"  },
    {   word: "USA",   category: "Państwa",    hint: "AMERYKA"  },
    {   word: "USA",   category: "Państwa",    hint: "AMERYKA"  },
    {   word: "USA",   category: "Państwa",    hint: "AMERYKA"  },
    {   word: "USA",   category: "Państwa",    hint: "AMERYKA"  },
    {   word: "USA",   category: "Państwa",    hint: "AMERYKA"  },
    {   word: "USA",   category: "Państwa",    hint: "AMERYKA"  },
    {   word: "USA",   category: "Państwa",    hint: "AMERYKA"  },
    {   word: "USA",   category: "Państwa",    hint: "AMERYKA"  },
    {   word: "USA",   category: "Państwa",    hint: "AMERYKA"  },
    {   word: "USA",   category: "Państwa",    hint: "AMERYKA"  },
    {   word: "USA",   category: "Państwa",    hint: "AMERYKA"  },
    {   word: "USA",   category: "Państwa",    hint: "AMERYKA"  },
    {   word: "USA",   category: "Państwa",    hint: "AMERYKA"  },
    {   word: "USA",   category: "Państwa",    hint: "AMERYKA"  },
    {   word: "USA",   category: "Państwa",    hint: "AMERYKA"  },
    {   word: "USA",   category: "Państwa",    hint: "AMERYKA"  },
    {   word: "USA",   category: "Państwa",    hint: "AMERYKA"  },
    {   word: "USA",   category: "Państwa",    hint: "AMERYKA"  },
    {   word: "USA",   category: "Państwa",    hint: "AMERYKA"  },
    {   word: "USA",   category: "Państwa",    hint: "AMERYKA"  },
    {   word: "USA",   category: "Państwa",    hint: "AMERYKA"  },


];